- project:
    name: openstack/networking-bigswitch
    templates:
      - system-required
      - openstack-python-jobs-neutron
      - openstack-python-jobs-trusty
      - publish-to-pypi
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: openstack/neutron
              - name: openstack/tap-as-a-service
        - openstack-tox-py27:
            required-projects:
              - name: openstack/neutron
              - name: openstack/tap-as-a-service
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: openstack/neutron
              - name: openstack/tap-as-a-service
        - openstack-tox-py27:
            required-projects:
              - name: openstack/neutron
              - name: openstack/tap-as-a-service
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - name: openstack/neutron
              - name: openstack/tap-as-a-service
