- project:
    name: openstack/networking-bigswitch
    templates:
      - system-required
      - openstack-python-jobs-neutron
      - openstack-python-jobs-trusty
      - publish-to-pypi
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              override_checkout: newton-eol
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron
              override_checkout: newton-eol
